name: last_mafconvert
description: Convert alignments in a MAF file to another format
keywords:
  - LAST
  - convert
  - alignment
  - MAF
tools:
  - last:
      description: LAST finds & aligns related regions of sequences.
      homepage: https://gitlab.com/mcfrith/last
      documentation: https://gitlab.com/mcfrith/last/-/blob/main/doc/
      tool_dev_url: https://gitlab.com/mcfrith/last
      doi: ""
      licence: ['GPL-3.0-or-later']

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - maf:
      type: file
      description: Multiple Aligment Format (MAF) file, optionally compressed with gzip
      pattern: "*.{maf.gz,maf}"

output:
  - gff:
      type: file
      description: General feature format (GFF) file, compressed with gzip
      pattern: "*.{gff.gz}"
  - axt:
      type: file
      description: Multiple alignment file in AXT format, compressed with gzip
      pattern: "*.{axt.gz}"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@charles-plessy"
